# decrypt deployment private key
before_install:
  - openssl aes-256-cbc -K $encrypted_3d83f42c7c33_key -iv $encrypted_3d83f42c7c33_iv -in kingsgate5-travis.enc -out kingsgate5-travis -d
  - chmod 0600 kingsgate5-travis

# install hugo
install:
  - wget https://github.com/spf13/hugo/releases/download/v0.18.1/hugo_0.18.1_Linux-64bit.tar.gz
  - tar xzvf hugo_0.18.1_Linux-64bit.tar.gz

# build the site
script: 
  - ./hugo_0.18.1_linux_amd64/hugo_0.18.1_linux_amd64 --theme=sunblind

# deploy it!
after_success:
  - cd public
  - scp -i ../kingsgate5-travis -o StrictHostKeyChecking=no -r * kingsgate5@kingsgate5.com:kingsgate5.com

